name: Deploy Prod
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load environment variables
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: /home/kdadmin/apps/vacancy/.front.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: localhost:5050/vacancy-front:main
          secret-files: |
            "env_file=/home/kdadmin/apps/vacancy/.front.env"
          cache-from: type=registry,ref=localhost:5050/vacancy-front:cache
          cache-to: type=registry,ref=localhost:5050/vacancy-front:cache,mode=max

      - name: Restart Docker Compose
        working-directory: /home/kdadmin/apps/vacancy
        run: |
          docker compose pull vacancy-frontend
          docker compose up -d vacancy-frontend
