name: Deploy Prod
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load environment variables
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: /home/kdadmin/apps/vacancy/.front.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build \
            --no-cache \
            --build-arg VITE_VACANT_API=${{ steps.dotenv.outputs.VITE_VACANT_API }} \
            --build-arg VITE_ADMIN_API=${{ steps.dotenv.outputs.VITE_ADMIN_API }} \
            --build-arg VITE_ADMIN_API_BACKED=${{ steps.dotenv.outputs.VITE_ADMIN_API_BACKED }} \
            --build-arg VITE_MAPS_API=${{ steps.dotenv.outputs.VITE_MAPS_API }} \
            --build-arg VITE_BASE_URL=${{ steps.dotenv.outputs.VITE_BASE_URL }} \
            -t localhost:5050/vacancy-front:main .

      - name: Push Docker Image to Local Registry
        run: |
          docker push localhost:5050/vacancy-front:main

      - name: Restart Docker Compose
        working-directory: /home/kdadmin/apps/vacancy
        run: |
          docker compose pull vacancy-frontend
          docker compose up -d vacancy-frontend
